" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
filetype indent plugin on

" Enable syntax highlighting
syntax on

" Better command-line completion
set wildmenu
set showcmd

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Display line numbers
set number

" Disable wrapping
set nowrap

" Don't litter swp files everywhere
set backupdir=~/.cache
set directory=~/.cache

" Enable backspace
set backspace=indent,eol,start

" Remap leader key to space
nnoremap <Space> <Nop>
let mapleader="\<Space>"

" Gruvbox setup
let &t_ut=''
let g:airline_theme = 'gruvbox'
let g:gruvbox_contrast_light = 'hard'
colorscheme gruvbox

" Mappings
nnoremap <Leader>n :set invnumber <CR> :GitGutterToggle <CR>

