" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
filetype indent plugin on

" Enable syntax highlighting
syntax on

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Always display the status line, even if only one window is displayed
set laststatus=2

" Display line numbers on the left
set number

" Timeout
set notimeout

" gitgutter refresh time
set updatetime=100

" Enable backspace
set backspace=indent,eol,start

" Airline
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

" Ctrl-P
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" gruvbox
let &t_ut=''
set termguicolors
set background=light
colorscheme gruvbox-material
let g:airline_theme = 'gruvbox_material'
